export interface Element {
  number: number
  symbol: string
  name: string
  type: ElementType
  period: number
  column: number
  atomicWeight: number | string
  // https://en.wikipedia.org/wiki/Electron_affinity_(data_page)
  electronAffinity: number
  // https://en.wikipedia.org/wiki/Ionization_energies_of_the_elements_(data_page)
  firstIonizationEnergy: number
  secondIonizationEnergy: number
  thirdIonizationEnergy: number
}

export enum ElementType {
  ALKALI_METAL,
  ALKALINE_EARTH_METAL,
  LANTHANOID,
  ACTINOID,
  TRANSITION_METAL,
  POST_TRANSITION_METAL,
  METALLOID,
  NOBLE_GAS,
  OTHER_NONMETAL,
}

const elements: Element[] = [
  {
    number: 1,
    type: ElementType.OTHER_NONMETAL,
    symbol: 'H',
    name: 'Hydrogen',
    period: 1,
    column: 1,
    atomicWeight: 1.008,
    electronAffinity: 72.788,
    firstIonizationEnergy: 1312,
    secondIonizationEnergy: null,
    thirdIonizationEnergy: null,
  },
  {
    number: 2,
    type: ElementType.NOBLE_GAS,
    symbol: 'He',
    name: 'Helium',
    period: 1,
    column: 18,
    atomicWeight: 4.0026,
    electronAffinity: -48,
    firstIonizationEnergy: 2372.3,
    secondIonizationEnergy: 5250.5,
    thirdIonizationEnergy: null,
  },
  {
    number: 3,
    type: ElementType.ALKALI_METAL,
    symbol: 'Li',
    name: 'Lithium',
    period: 2,
    column: 1,
    atomicWeight: 6.94,
    electronAffinity: 59.632,
    firstIonizationEnergy: 520.2,
    secondIonizationEnergy: 7298.1,
    thirdIonizationEnergy: 11815,
  },
  {
    number: 4,
    type: ElementType.ALKALINE_EARTH_METAL,
    symbol: 'Be',
    name: 'Beryllium',
    period: 2,
    column: 2,
    atomicWeight: 9.0122,
    electronAffinity: -48,
    firstIonizationEnergy: 899.5,
    secondIonizationEnergy: 1757.1,
    thirdIonizationEnergy: 14848.7,
  },
  {
    number: 5,
    type: ElementType.METALLOID,
    symbol: 'B',
    name: 'Boron',
    period: 2,
    column: 13,
    atomicWeight: 10.81,
    electronAffinity: 26.989,
    firstIonizationEnergy: 800.6,
    secondIonizationEnergy: 2427.1,
    thirdIonizationEnergy: 3659.7,
  },
  {
    number: 6,
    type: ElementType.OTHER_NONMETAL,
    symbol: 'C',
    name: 'Carbon',
    period: 2,
    column: 14,
    atomicWeight: 12.011,
    electronAffinity: 121.776,
    firstIonizationEnergy: 1086.5,
    secondIonizationEnergy: 2352.6,
    thirdIonizationEnergy: 4620.5,
  },
  {
    number: 7,
    type: ElementType.OTHER_NONMETAL,
    symbol: 'N',
    name: 'Nitrogen',
    period: 2,
    column: 15,
    atomicWeight: 14.007,
    electronAffinity: -6.8,
    firstIonizationEnergy: 1402.3,
    secondIonizationEnergy: 2856,
    thirdIonizationEnergy: 4578.1,
  },
  {
    number: 8,
    type: ElementType.OTHER_NONMETAL,
    symbol: 'O',
    name: 'Oxygen',
    period: 2,
    column: 16,
    atomicWeight: 15.999,
    electronAffinity: 140.975,
    firstIonizationEnergy: 1313.9,
    secondIonizationEnergy: 3388.3,
    thirdIonizationEnergy: 5300.5,
  },
  {
    number: 9,
    type: ElementType.OTHER_NONMETAL,
    symbol: 'F',
    name: 'Fluorine',
    period: 2,
    column: 17,
    atomicWeight: 18.998,
    electronAffinity: 328.164,
    firstIonizationEnergy: 1681,
    secondIonizationEnergy: 3374.2,
    thirdIonizationEnergy: 6050.4,
  },
  {
    number: 10,
    type: ElementType.NOBLE_GAS,
    symbol: 'Ne',
    name: 'Neon',
    period: 2,
    column: 18,
    atomicWeight: 20.180,
    electronAffinity: -116,
    firstIonizationEnergy: 2080.7,
    secondIonizationEnergy: 3952.3,
    thirdIonizationEnergy: 6122,
  },
  {
    number: 11,
    type: ElementType.ALKALI_METAL,
    symbol: 'Na',
    name: 'Sodium',
    period: 3,
    column: 1,
    atomicWeight: 22.990,
    electronAffinity: 52.867,
    firstIonizationEnergy: 495.8,
    secondIonizationEnergy: 4562,
    thirdIonizationEnergy: 6910.3,
  },
  {
    number: 12,
    type: ElementType.ALKALINE_EARTH_METAL,
    symbol: 'Mg',
    name: 'Magnesium',
    period: 3,
    column: 2,
    atomicWeight: 24.305,
    electronAffinity: -40,
    firstIonizationEnergy: 737.7,
    secondIonizationEnergy: 1450.7,
    thirdIonizationEnergy: 7732.7,
  },
  {
    number: 13,
    type: ElementType.POST_TRANSITION_METAL,
    symbol: 'Al',
    name: 'Aluminium',
    period: 3,
    column: 13,
    atomicWeight: 26.982,
    electronAffinity: 41.762,
    firstIonizationEnergy: 577.5,
    secondIonizationEnergy: 1816.7,
    thirdIonizationEnergy: 2744.8,
  },
  {
    number: 14,
    type: ElementType.METALLOID,
    symbol: 'Si',
    name: 'Silicon',
    period: 3,
    column: 14,
    atomicWeight: 28.085,
    electronAffinity: 134.068,
    firstIonizationEnergy: 786.5,
    secondIonizationEnergy: 1577.1,
    thirdIonizationEnergy: 3231.6,
  },
  {
    number: 15,
    type: ElementType.OTHER_NONMETAL,
    symbol: 'P',
    name: 'Phosphorus',
    period: 3,
    column: 15,
    atomicWeight: 30.974,
    electronAffinity: 72.037,
    firstIonizationEnergy: 1011.8,
    secondIonizationEnergy: 1907,
    thirdIonizationEnergy: 2914.1,
  },
  {
    number: 16,
    type: ElementType.OTHER_NONMETAL,
    symbol: 'S',
    name: 'Sulfur',
    period: 3,
    column: 16,
    atomicWeight: 32.06,
    electronAffinity: 200.410,
    firstIonizationEnergy: 999.6,
    secondIonizationEnergy: 2252,
    thirdIonizationEnergy: 3357,
  },
  {
    number: 17,
    type: ElementType.OTHER_NONMETAL,
    symbol: 'Cl',
    name: 'Chlorine',
    period: 3,
    column: 17,
    atomicWeight: 35.45,
    electronAffinity: 348.575,
    firstIonizationEnergy: 1251.2,
    secondIonizationEnergy: 2298,
    thirdIonizationEnergy: 3822,
  },
  {
    number: 18,
    type: ElementType.NOBLE_GAS,
    symbol: 'Ar',
    name: 'Argon',
    period: 3,
    column: 18,
    atomicWeight: 39.948,
    electronAffinity: -96,
    firstIonizationEnergy: 1520.6,
    secondIonizationEnergy: 2665.8,
    thirdIonizationEnergy: 3931,
  },
  {
    number: 19,
    type: ElementType.ALKALI_METAL,
    symbol: 'K',
    name: 'Potassium',
    period: 4,
    column: 1,
    atomicWeight: 39.098,
    electronAffinity: 48.383,
    firstIonizationEnergy: 418.8,
    secondIonizationEnergy: 3052,
    thirdIonizationEnergy: 4420,
  },
  {
    number: 20,
    type: ElementType.ALKALINE_EARTH_METAL,
    symbol: 'Ca',
    name: 'Calcium',
    period: 4,
    column: 2,
    atomicWeight: 40.078,
    electronAffinity: 2.37,
    firstIonizationEnergy: 589.8,
    secondIonizationEnergy: 1145.4,
    thirdIonizationEnergy: 4912.4,
  },
  {
    number: 21,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Sc',
    name: 'Scandium',
    period: 4,
    column: 3,
    atomicWeight: 44.956,
    electronAffinity: 18,
    firstIonizationEnergy: 633.1,
    secondIonizationEnergy: 1235,
    thirdIonizationEnergy: 2388.6,
  },
  {
    number: 22,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Ti',
    name: 'Titanium',
    period: 4,
    column: 4,
    atomicWeight: 47.867,
    electronAffinity: 7.289,
    firstIonizationEnergy: 658.8,
    secondIonizationEnergy: 1309.8,
    thirdIonizationEnergy: 2652.5,
  },
  {
    number: 23,
    type: ElementType.TRANSITION_METAL,
    symbol: 'V',
    name: 'Vanadium',
    period: 4,
    column: 5,
    atomicWeight: 50.942,
    electronAffinity: 50.911,
    firstIonizationEnergy: 650.9,
    secondIonizationEnergy: 1414,
    thirdIonizationEnergy: 2830,
  },
  {
    number: 24,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Cr',
    name: 'Chromium',
    period: 4,
    column: 6,
    atomicWeight: 51.996,
    electronAffinity: 65.21,
    firstIonizationEnergy: 652.9,
    secondIonizationEnergy: 1590.6,
    thirdIonizationEnergy: 2987,
  },
  {
    number: 25,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Mn',
    name: 'Manganese',
    period: 4,
    column: 7,
    atomicWeight: 54.938,
    electronAffinity: -50,
    firstIonizationEnergy: 717.3,
    secondIonizationEnergy: 1509,
    thirdIonizationEnergy: 3248,
  },
  {
    number: 26,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Fe',
    name: 'Iron',
    period: 4,
    column: 8,
    atomicWeight: 55.845,
    electronAffinity: 14.785,
    firstIonizationEnergy: 762.5,
    secondIonizationEnergy: 1561.9,
    thirdIonizationEnergy: 2957,
  },
  {
    number: 27,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Co',
    name: 'Cobalt',
    period: 4,
    column: 9,
    atomicWeight: 58.933,
    electronAffinity: 63.898,
    firstIonizationEnergy: 760.4,
    secondIonizationEnergy: 1648,
    thirdIonizationEnergy: 3232,
  },
  {
    number: 28,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Ni',
    name: 'Nickel',
    period: 4,
    column: 10,
    atomicWeight: 58.693,
    electronAffinity: 111.65,
    firstIonizationEnergy: 737.1,
    secondIonizationEnergy: 1753,
    thirdIonizationEnergy: 3395,
  },
  {
    number: 29,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Cu',
    name: 'Copper',
    period: 4,
    column: 11,
    atomicWeight: 63.546,
    electronAffinity: 119.235,
    firstIonizationEnergy: 745.5,
    secondIonizationEnergy: 1957.9,
    thirdIonizationEnergy: 3555,
  },
  {
    number: 30,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Zn',
    name: 'Zinc',
    period: 4,
    column: 12,
    atomicWeight: 65.38,
    electronAffinity: -58,
    firstIonizationEnergy: 906.4,
    secondIonizationEnergy: 1733.3,
    thirdIonizationEnergy: 3833,
  },
  {
    number: 31,
    type: ElementType.POST_TRANSITION_METAL,
    symbol: 'Ga',
    name: 'Gallium',
    period: 4,
    column: 13,
    atomicWeight: 69.723,
    electronAffinity: 29.061,
    firstIonizationEnergy: 578.8,
    secondIonizationEnergy: 1979.3,
    thirdIonizationEnergy: 2963,
  },
  {
    number: 32,
    type: ElementType.METALLOID,
    symbol: 'Ge',
    name: 'Germanium',
    period: 4,
    column: 14,
    atomicWeight: 72.630,
    electronAffinity: 118.935,
    firstIonizationEnergy: 762,
    secondIonizationEnergy: 1537.5,
    thirdIonizationEnergy: 3302.1,
  },
  {
    number: 33,
    type: ElementType.METALLOID,
    symbol: 'As',
    name: 'Arsenic',
    period: 4,
    column: 15,
    atomicWeight: 74.922,
    electronAffinity: 77.65,
    firstIonizationEnergy: 947,
    secondIonizationEnergy: 1798,
    thirdIonizationEnergy: 2735,
  },
  {
    number: 34,
    type: ElementType.OTHER_NONMETAL,
    symbol: 'Se',
    name: 'Selenium',
    period: 4,
    column: 16,
    atomicWeight: 78.971,
    electronAffinity: 194.958,
    firstIonizationEnergy: 941,
    secondIonizationEnergy: 2045,
    thirdIonizationEnergy: 2973.7,
  },
  {
    number: 35,
    type: ElementType.OTHER_NONMETAL,
    symbol: 'Br',
    name: 'Bromine',
    period: 4,
    column: 17,
    atomicWeight: 79.904,
    electronAffinity: 324.536,
    firstIonizationEnergy: 1139.9,
    secondIonizationEnergy: 2103,
    thirdIonizationEnergy: 3470,
  },
  {
    number: 36,
    type: ElementType.NOBLE_GAS,
    symbol: 'Kr',
    name: 'Krypton',
    period: 4,
    column: 18,
    atomicWeight: 83.798,
    electronAffinity: -96,
    firstIonizationEnergy: 1350.8,
    secondIonizationEnergy: 2350.4,
    thirdIonizationEnergy: 3565,
  },
  {
    number: 37,
    type: ElementType.ALKALI_METAL,
    symbol: 'Rb',
    name: 'Rubidium',
    period: 5,
    column: 1,
    atomicWeight: 85.468,
    electronAffinity: 46.884,
    firstIonizationEnergy: 403,
    secondIonizationEnergy: 2633,
    thirdIonizationEnergy: 3860,
  },
  {
    number: 38,
    type: ElementType.ALKALINE_EARTH_METAL,
    symbol: 'Sr',
    name: 'Strontium',
    period: 5,
    column: 2,
    atomicWeight: 87.62,
    electronAffinity: 5.023,
    firstIonizationEnergy: 549.5,
    secondIonizationEnergy: 1064.2,
    thirdIonizationEnergy: 4138,
  },
  {
    number: 39,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Y',
    name: 'Yttrium',
    period: 5,
    column: 3,
    atomicWeight: 88.906,
    electronAffinity: 29.6,
    firstIonizationEnergy: 600,
    secondIonizationEnergy: 1180,
    thirdIonizationEnergy: 1980,
  },
  {
    number: 40,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Zr',
    name: 'Zirconium',
    period: 5,
    column: 4,
    atomicWeight: 91.224,
    electronAffinity: 41.806,
    firstIonizationEnergy: 640.1,
    secondIonizationEnergy: 1270,
    thirdIonizationEnergy: 2218,
  },
  {
    number: 41,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Nb',
    name: 'Niobium',
    period: 5,
    column: 5,
    atomicWeight: 92.906,
    electronAffinity: 88.516,
    firstIonizationEnergy: 652.1,
    secondIonizationEnergy: 1380,
    thirdIonizationEnergy: 2416,
  },
  {
    number: 42,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Mo',
    name: 'Molybdenum',
    period: 5,
    column: 6,
    atomicWeight: 95.95,
    electronAffinity: 72.10,
    firstIonizationEnergy: 684.3,
    secondIonizationEnergy: 1560,
    thirdIonizationEnergy: 2618,
  },
  {
    number: 43,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Tc',
    name: 'Technetium',
    period: 5,
    column: 7,
    atomicWeight: '(98)',
    electronAffinity: 53,
    firstIonizationEnergy: 702,
    secondIonizationEnergy: 1470,
    thirdIonizationEnergy: 2850,
  },
  {
    number: 44,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Ru',
    name: 'Ruthenium',
    period: 5,
    column: 8,
    atomicWeight: 101.07,
    electronAffinity: 100.96,
    firstIonizationEnergy: 710.2,
    secondIonizationEnergy: 1620,
    thirdIonizationEnergy: 2747,
  },
  {
    number: 45,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Rh',
    name: 'Rhodium',
    period: 5,
    column: 9,
    atomicWeight: 102.91,
    electronAffinity: 110.27,
    firstIonizationEnergy: 719.7,
    secondIonizationEnergy: 1740,
    thirdIonizationEnergy: 2997,
  },
  {
    number: 46,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Pd',
    name: 'Palladium',
    period: 5,
    column: 10,
    atomicWeight: 106.42,
    electronAffinity: 54.24,
    firstIonizationEnergy: 804.4,
    secondIonizationEnergy: 1870,
    thirdIonizationEnergy: 3177,
  },
  {
    number: 47,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Ag',
    name: 'Silver',
    period: 5,
    column: 11,
    atomicWeight: 107.87,
    electronAffinity: 125.862,
    firstIonizationEnergy: 731,
    secondIonizationEnergy: 2070,
    thirdIonizationEnergy: 3361,
  },
  {
    number: 48,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Cd',
    name: 'Cadmium',
    period: 5,
    column: 12,
    atomicWeight: 112.41,
    electronAffinity: -68,
    firstIonizationEnergy: 867.8,
    secondIonizationEnergy: 1631.4,
    thirdIonizationEnergy: 3616,
  },
  {
    number: 49,
    type: ElementType.POST_TRANSITION_METAL,
    symbol: 'In',
    name: 'Indium',
    period: 5,
    column: 13,
    atomicWeight: 114.82,
    electronAffinity: 37.043,
    firstIonizationEnergy: 558.3,
    secondIonizationEnergy: 1820.7,
    thirdIonizationEnergy: 2704,
  },
  {
    number: 50,
    type: ElementType.POST_TRANSITION_METAL,
    symbol: 'Sn',
    name: 'Tin',
    period: 5,
    column: 14,
    atomicWeight: 118.71,
    electronAffinity: 107.298,
    firstIonizationEnergy: 708.6,
    secondIonizationEnergy: 1411.8,
    thirdIonizationEnergy: 2943,
  },
  {
    number: 51,
    type: ElementType.METALLOID,
    symbol: 'Sb',
    name: 'Antimony',
    period: 5,
    column: 15,
    atomicWeight: 121.76,
    electronAffinity: 101.059,
    firstIonizationEnergy: 834,
    secondIonizationEnergy: 1594.9,
    thirdIonizationEnergy: 2440,
  },
  {
    number: 52,
    type: ElementType.METALLOID,
    symbol: 'Te',
    name: 'Tellurium',
    period: 5,
    column: 16,
    atomicWeight: 127.60,
    electronAffinity: 190.161,
    firstIonizationEnergy: 869.3,
    secondIonizationEnergy: 1790,
    thirdIonizationEnergy: 2698,
  },
  {
    number: 53,
    type: ElementType.OTHER_NONMETAL,
    symbol: 'I',
    name: 'Iodine',
    period: 5,
    column: 17,
    atomicWeight: 126.90,
    electronAffinity: 295.154,
    firstIonizationEnergy: 1008.4,
    secondIonizationEnergy: 1845.9,
    thirdIonizationEnergy: 3180,
  },
  {
    number: 54,
    type: ElementType.NOBLE_GAS,
    symbol: 'Xe',
    name: 'Xenon',
    period: 5,
    column: 18,
    atomicWeight: 131.29,
    electronAffinity: -77,
    firstIonizationEnergy: 1170.4,
    secondIonizationEnergy: 2046.4,
    thirdIonizationEnergy: 3099.4,
  },
  {
    number: 55,
    type: ElementType.ALKALI_METAL,
    symbol: 'Cs',
    name: 'Caesium',
    period: 6,
    column: 1,
    atomicWeight: 132.91,
    electronAffinity: 45.505,
    firstIonizationEnergy: 375.7,
    secondIonizationEnergy: 2234.3,
    thirdIonizationEnergy: 3400,
  },
  {
    number: 56,
    type: ElementType.ALKALINE_EARTH_METAL,
    symbol: 'Ba',
    name: 'Barium',
    period: 6,
    column: 2,
    atomicWeight: 137.33,
    electronAffinity: 13.954,
    firstIonizationEnergy: 502.9,
    secondIonizationEnergy: 965.2,
    thirdIonizationEnergy: 3600,
  },
  {
    number: 57,
    type: ElementType.LANTHANOID,
    symbol: 'La',
    name: 'Lanthanum',
    period: 6,
    column: null,
    atomicWeight: 138.91,
    electronAffinity: 53.795,
    firstIonizationEnergy: 538.1,
    secondIonizationEnergy: 1067,
    thirdIonizationEnergy: 1850.3,
  },
  {
    number: 58,
    type: ElementType.LANTHANOID,
    symbol: 'Ce',
    name: 'Cerium',
    period: 6,
    column: null,
    atomicWeight: 140.12,
    electronAffinity: 55,
    firstIonizationEnergy: 534.4,
    secondIonizationEnergy: 1050,
    thirdIonizationEnergy: 1949,
  },
  {
    number: 59,
    type: ElementType.LANTHANOID,
    symbol: 'Pr',
    name: 'Praseodymium',
    period: 6,
    column: null,
    atomicWeight: 140.91,
    electronAffinity: 10.539,
    firstIonizationEnergy: 527,
    secondIonizationEnergy: 1020,
    thirdIonizationEnergy: 2086,
  },
  {
    number: 60,
    type: ElementType.LANTHANOID,
    symbol: 'Nd',
    name: 'Neodymium',
    period: 6,
    column: null,
    atomicWeight: 144.24,
    electronAffinity: 9.406,
    firstIonizationEnergy: 533.1,
    secondIonizationEnergy: 1040,
    thirdIonizationEnergy: 2130,
  },
  {
    number: 61,
    type: ElementType.LANTHANOID,
    symbol: 'Pm',
    name: 'Promethium',
    period: 6,
    column: null,
    atomicWeight: '(145)',
    electronAffinity: 12.45,
    firstIonizationEnergy: 540,
    secondIonizationEnergy: 1050,
    thirdIonizationEnergy: 2150,
  },
  {
    number: 62,
    type: ElementType.LANTHANOID,
    symbol: 'Sm',
    name: 'Samarium',
    period: 6,
    column: null,
    atomicWeight: 150.36,
    electronAffinity: 15.63,
    firstIonizationEnergy: 544.5,
    secondIonizationEnergy: 1070,
    thirdIonizationEnergy: 2260,
  },
  {
    number: 63,
    type: ElementType.LANTHANOID,
    symbol: 'Eu',
    name: 'Europium',
    period: 6,
    column: null,
    atomicWeight: 151.96,
    electronAffinity: 11.2,
    firstIonizationEnergy: 547.1,
    secondIonizationEnergy: 1085,
    thirdIonizationEnergy: 2404,
  },
  {
    number: 64,
    type: ElementType.LANTHANOID,
    symbol: 'Gd',
    name: 'Gadolinium',
    period: 6,
    column: null,
    atomicWeight: 157.25,
    electronAffinity: 13.22,
    firstIonizationEnergy: 593.4,
    secondIonizationEnergy: 1170,
    thirdIonizationEnergy: 1990,
  },
  {
    number: 65,
    type: ElementType.LANTHANOID,
    symbol: 'Tb',
    name: 'Terbium',
    period: 6,
    column: null,
    atomicWeight: 158.93,
    electronAffinity: 12.670,
    firstIonizationEnergy: 565.8,
    secondIonizationEnergy: 1110,
    thirdIonizationEnergy: 2114,
  },
  {
    number: 66,
    type: ElementType.LANTHANOID,
    symbol: 'Dy',
    name: 'Dysprosium',
    period: 6,
    column: null,
    atomicWeight: 162.50,
    electronAffinity: 33.96,
    firstIonizationEnergy: 573,
    secondIonizationEnergy: 1130,
    thirdIonizationEnergy: 2200,
  },
  {
    number: 67,
    type: ElementType.LANTHANOID,
    symbol: 'Ho',
    name: 'Holmium',
    period: 6,
    column: null,
    atomicWeight: 164.93,
    electronAffinity: 32.61,
    firstIonizationEnergy: 581,
    secondIonizationEnergy: 1140,
    thirdIonizationEnergy: 2204,
  },
  {
    number: 68,
    type: ElementType.LANTHANOID,
    symbol: 'Er',
    name: 'Erbium',
    period: 6,
    column: null,
    atomicWeight: 167.26,
    electronAffinity: 30.10,
    firstIonizationEnergy: 589.3,
    secondIonizationEnergy: 1150,
    thirdIonizationEnergy: 2194,
  },
  {
    number: 69,
    type: ElementType.LANTHANOID,
    symbol: 'Tm',
    name: 'Thulium',
    period: 6,
    column: null,
    atomicWeight: 168.93,
    electronAffinity: 99,
    firstIonizationEnergy: 596.7,
    secondIonizationEnergy: 1160,
    thirdIonizationEnergy: 2285,
  },
  {
    number: 70,
    type: ElementType.LANTHANOID,
    symbol: 'Yb',
    name: 'Ytterbium',
    period: 6,
    column: null,
    atomicWeight: 173.05,
    electronAffinity: -1.93,
    firstIonizationEnergy: 603.4,
    secondIonizationEnergy: 1174.8,
    thirdIonizationEnergy: 2417,
  },
  {
    number: 71,
    type: ElementType.LANTHANOID,
    symbol: 'Lu',
    name: 'Lutetium',
    period: 6,
    column: null,
    atomicWeight: 174.97,
    electronAffinity: 23.04,
    firstIonizationEnergy: 523.5,
    secondIonizationEnergy: 1340,
    thirdIonizationEnergy: 2022.3,
  },
  {
    number: 72,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Ha',
    name: 'Hafnium',
    period: 6,
    column: 4,
    atomicWeight: 178.49,
    electronAffinity: 17.18,
    firstIonizationEnergy: 658.5,
    secondIonizationEnergy: 1440,
    thirdIonizationEnergy: 2250,
  },
  {
    number: 73,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Tf',
    name: 'Tantalum',
    period: 6,
    column: 5,
    atomicWeight: 180.95,
    electronAffinity: 31,
    firstIonizationEnergy: 761,
    secondIonizationEnergy: 1500,
    thirdIonizationEnergy: null,
  },
  {
    number: 74,
    type: ElementType.TRANSITION_METAL,
    symbol: 'W',
    name: 'Tungsten',
    period: 6,
    column: 6,
    atomicWeight: 183.84,
    electronAffinity: 78.76,
    firstIonizationEnergy: 770,
    secondIonizationEnergy: 1700,
    thirdIonizationEnergy: null,
  },
  {
    number: 75,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Re',
    name: 'Rhenium',
    period: 6,
    column: 7,
    atomicWeight: 186.21,
    electronAffinity: 5.8273,
    firstIonizationEnergy: 760,
    secondIonizationEnergy: 1260,
    thirdIonizationEnergy: 2510,
  },
  {
    number: 76,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Os',
    name: 'Osmium',
    period: 6,
    column: 8,
    atomicWeight: 190.23,
    electronAffinity: 103.99,
    firstIonizationEnergy: 840,
    secondIonizationEnergy: 1600,
    thirdIonizationEnergy: null,
  },
  {
    number: 77,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Ir',
    name: 'Iridium',
    period: 6,
    column: 9,
    atomicWeight: 192.22,
    electronAffinity: 150.94,
    firstIonizationEnergy: 880,
    secondIonizationEnergy: 1600,
    thirdIonizationEnergy: null,
  },
  {
    number: 78,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Pt',
    name: 'Platinum',
    period: 6,
    column: 10,
    atomicWeight: 195.08,
    electronAffinity: 205.041,
    firstIonizationEnergy: 870,
    secondIonizationEnergy: 1791,
    thirdIonizationEnergy: null,
  },
  {
    number: 79,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Ag',
    name: 'Gold',
    period: 6,
    column: 11,
    atomicWeight: 196.97,
    electronAffinity: 222.747,
    firstIonizationEnergy: 890.1,
    secondIonizationEnergy: 1980,
    thirdIonizationEnergy: null,
  },
  {
    number: 80,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Hg',
    name: 'Mercury',
    period: 6,
    column: 12,
    atomicWeight: 200.59,
    electronAffinity: -48,
    firstIonizationEnergy: 1007.1,
    secondIonizationEnergy: 1810,
    thirdIonizationEnergy: 3300,
  },
  {
    number: 81,
    type: ElementType.POST_TRANSITION_METAL,
    symbol: 'Tl',
    name: 'Thallium',
    period: 6,
    column: 13,
    atomicWeight: 204.38,
    electronAffinity: 36.4,
    firstIonizationEnergy: 589.4,
    secondIonizationEnergy: 1971,
    thirdIonizationEnergy: 2878,
  },
  {
    number: 82,
    type: ElementType.POST_TRANSITION_METAL,
    symbol: 'Pb',
    name: 'Lead',
    period: 6,
    column: 14,
    atomicWeight: 207.2,
    electronAffinity: 34.4183,
    firstIonizationEnergy: 715.6,
    secondIonizationEnergy: 1450.5,
    thirdIonizationEnergy: 3081.5,
  },
  {
    number: 83,
    type: ElementType.POST_TRANSITION_METAL,
    symbol: 'Bi',
    name: 'Bismuth',
    period: 6,
    column: 15,
    atomicWeight: 208.98,
    electronAffinity: 90.924,
    firstIonizationEnergy: 703,
    secondIonizationEnergy: 1610,
    thirdIonizationEnergy: 2466,
  },
  {
    number: 84,
    type: ElementType.POST_TRANSITION_METAL,
    symbol: 'Po',
    name: 'Polonium',
    period: 6,
    column: 16,
    atomicWeight: '(209)',
    electronAffinity: 136,
    firstIonizationEnergy: 812.1,
    secondIonizationEnergy: null,
    thirdIonizationEnergy: null,
  },
  {
    number: 85,
    type: ElementType.METALLOID,
    symbol: 'At',
    name: 'Astatine',
    period: 6,
    column: 17,
    atomicWeight: '(210)',
    electronAffinity: 233,
    firstIonizationEnergy: 899.003,
    secondIonizationEnergy: null,
    thirdIonizationEnergy: null,
  },
  {
    number: 86,
    type: ElementType.NOBLE_GAS,
    symbol: 'Rn',
    name: 'Radon',
    period: 6,
    column: 18,
    atomicWeight: '(222)',
    electronAffinity: -68,
    firstIonizationEnergy: 1037,
    secondIonizationEnergy: null,
    thirdIonizationEnergy: null,
  },
  {
    number: 87,
    type: ElementType.ALKALI_METAL,
    symbol: 'Fr',
    name: 'Francium',
    period: 7,
    column: 1,
    atomicWeight: '(223)',
    electronAffinity: 46.89,
    firstIonizationEnergy: 380,
    secondIonizationEnergy: null,
    thirdIonizationEnergy: null,
  },
  {
    number: 88,
    type: ElementType.ALKALI_METAL,
    symbol: 'Ra',
    name: 'Radium',
    period: 7,
    column: 2,
    atomicWeight: '(226)',
    electronAffinity: 9.6485,
    firstIonizationEnergy: 509.3,
    secondIonizationEnergy: 979,
    thirdIonizationEnergy: null,
  },
  {
    number: 89,
    type: ElementType.ACTINOID,
    symbol: 'Ac',
    name: 'Actinium',
    period: 7,
    column: null,
    atomicWeight: '(227)',
    electronAffinity: 33.77,
    firstIonizationEnergy: 499,
    secondIonizationEnergy: 1170,
    thirdIonizationEnergy: null,
  },
  {
    number: 90,
    type: ElementType.ACTINOID,
    symbol: 'Th',
    name: 'Thorium',
    period: 7,
    column: null,
    atomicWeight: 232.04,
    electronAffinity: 112.72,
    firstIonizationEnergy: 587,
    secondIonizationEnergy: 1110,
    thirdIonizationEnergy: 1930,
  },
  {
    number: 91,
    type: ElementType.ACTINOID,
    symbol: 'Pa',
    name: 'Protactinium',
    period: 7,
    column: null,
    atomicWeight: 231.04,
    electronAffinity: 53.03,
    firstIonizationEnergy: 568,
    secondIonizationEnergy: null,
    thirdIonizationEnergy: null,
  },
  {
    number: 92,
    type: ElementType.ACTINOID,
    symbol: 'U',
    name: 'Uranium',
    period: 7,
    column: null,
    atomicWeight: 238.03,
    electronAffinity: 50.94,
    firstIonizationEnergy: 597.6,
    secondIonizationEnergy: 1420,
    thirdIonizationEnergy: null,
  },
  {
    number: 93,
    type: ElementType.ACTINOID,
    symbol: 'Np',
    name: 'Neptunium',
    period: 7,
    column: null,
    atomicWeight: '(237)',
    electronAffinity: 45.85,
    firstIonizationEnergy: 604.5,
    secondIonizationEnergy: null,
    thirdIonizationEnergy: null,
  },
  {
    number: 94,
    type: ElementType.ACTINOID,
    symbol: 'Pu',
    name: 'Plutonium',
    period: 7,
    column: null,
    atomicWeight: '(244)',
    electronAffinity: -48.33,
    firstIonizationEnergy: 584.7,
    secondIonizationEnergy: null,
    thirdIonizationEnergy: null,
  },
  {
    number: 95,
    type: ElementType.ACTINOID,
    symbol: 'Am',
    name: 'Americium',
    period: 7,
    column: null,
    atomicWeight: '(243)',
    electronAffinity: 9.93,
    firstIonizationEnergy: 578,
    secondIonizationEnergy: null,
    thirdIonizationEnergy: null,
  },
  {
    number: 96,
    type: ElementType.ACTINOID,
    symbol: 'Cm',
    name: 'Curium',
    period: 7,
    column: null,
    atomicWeight: '(247)',
    electronAffinity: 27.17,
    firstIonizationEnergy: 581,
    secondIonizationEnergy: null,
    thirdIonizationEnergy: null,
  },
  {
    number: 97,
    type: ElementType.ACTINOID,
    symbol: 'Bk',
    name: 'Berkelium',
    period: 7,
    column: null,
    atomicWeight: '(247)',
    electronAffinity: -165.24,
    firstIonizationEnergy: 601,
    secondIonizationEnergy: null,
    thirdIonizationEnergy: null,
  },
  {
    number: 98,
    type: ElementType.ACTINOID,
    symbol: 'Cf',
    name: 'Californium',
    period: 7,
    column: null,
    atomicWeight: '(251)',
    electronAffinity: -97.31,
    firstIonizationEnergy: 608,
    secondIonizationEnergy: null,
    thirdIonizationEnergy: null,
  },
  {
    number: 99,
    type: ElementType.ACTINOID,
    symbol: 'Es',
    name: 'Einsteinium',
    period: 7,
    column: null,
    atomicWeight: '(252)',
    electronAffinity: -28.60,
    firstIonizationEnergy: 619,
    secondIonizationEnergy: null,
    thirdIonizationEnergy: null,
  },
  {
    number: 100,
    type: ElementType.ACTINOID,
    symbol: 'Fm',
    name: 'Fermium',
    period: 7,
    column: null,
    atomicWeight: '(257)',
    electronAffinity: 33.96,
    firstIonizationEnergy: 627,
    secondIonizationEnergy: null,
    thirdIonizationEnergy: null,
  },
  {
    number: 101,
    type: ElementType.ACTINOID,
    symbol: 'Md',
    name: 'Mendelevium',
    period: 7,
    column: null,
    atomicWeight: '(258)',
    electronAffinity: 93.91,
    firstIonizationEnergy: 635,
    secondIonizationEnergy: null,
    thirdIonizationEnergy: null,
  },
  {
    number: 102,
    type: ElementType.ACTINOID,
    symbol: 'No',
    name: 'Nobelium',
    period: 7,
    column: null,
    atomicWeight: '(259)',
    electronAffinity: -223.22,
    firstIonizationEnergy: 642,
    secondIonizationEnergy: null,
    thirdIonizationEnergy: null,
  },
  {
    number: 103,
    type: ElementType.ACTINOID,
    symbol: 'Lr',
    name: 'Lawrencium',
    period: 7,
    column: null,
    atomicWeight: '(266)',
    electronAffinity: -30.04,
    firstIonizationEnergy: 470,
    secondIonizationEnergy: null,
    thirdIonizationEnergy: null,
  },
  {
    number: 104,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Rf',
    name: 'Rutherfordium',
    period: 7,
    column: 4,
    atomicWeight: '(267)',
    electronAffinity: null,
    firstIonizationEnergy: 580,
    secondIonizationEnergy: null,
    thirdIonizationEnergy: null,
  },
  {
    number: 105,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Db',
    name: 'Dubnium',
    period: 7,
    column: 5,
    atomicWeight: '(268)',
    electronAffinity: null,
    firstIonizationEnergy: null,
    secondIonizationEnergy: null,
    thirdIonizationEnergy: null,
  },
  {
    number: 106,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Sg',
    name: 'Seaborgium',
    period: 7,
    column: 6,
    atomicWeight: '(269)',
    electronAffinity: null,
    firstIonizationEnergy: null,
    secondIonizationEnergy: null,
    thirdIonizationEnergy: null,
  },
  {
    number: 107,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Bh',
    name: 'Bohrium',
    period: 7,
    column: 7,
    atomicWeight: '(270)',
    electronAffinity: null,
    firstIonizationEnergy: null,
    secondIonizationEnergy: null,
    thirdIonizationEnergy: null,
  },
  {
    number: 108,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Hs',
    name: 'Hassium',
    period: 7,
    column: 8,
    atomicWeight: '(270)',
    electronAffinity: null,
    firstIonizationEnergy: null,
    secondIonizationEnergy: null,
    thirdIonizationEnergy: null,
  },
  {
    number: 109,
    type: null,
    symbol: 'Mt',
    name: 'Meitnerium',
    period: 7,
    column: 9,
    atomicWeight: '(278)',
    electronAffinity: null,
    firstIonizationEnergy: null,
    secondIonizationEnergy: null,
    thirdIonizationEnergy: null,
  },
  {
    number: 110,
    type: null,
    symbol: 'Ds',
    name: 'Darmstadtium',
    period: 7,
    column: 10,
    atomicWeight: '(281)',
    electronAffinity: null,
    firstIonizationEnergy: null,
    secondIonizationEnergy: null,
    thirdIonizationEnergy: null,
  },
  {
    number: 111,
    type: null,
    symbol: 'Rg',
    name: 'Roentgenium',
    period: 7,
    column: 11,
    atomicWeight: '(282)',
    electronAffinity: 151.0,
    firstIonizationEnergy: null,
    secondIonizationEnergy: null,
    thirdIonizationEnergy: null,
  },
  {
    number: 112,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Cn',
    name: 'Copernicium',
    period: 7,
    column: 12,
    atomicWeight: '(285)',
    electronAffinity: null,
    firstIonizationEnergy: null,
    secondIonizationEnergy: null,
    thirdIonizationEnergy: null,
  },
  {
    number: 113,
    type: null,
    symbol: 'Nh',
    name: 'Nihonium',
    period: 7,
    column: 13,
    atomicWeight: '(286)',
    electronAffinity: 66.6,
    firstIonizationEnergy: null,
    secondIonizationEnergy: null,
    thirdIonizationEnergy: null,
  },
  {
    number: 114,
    type: ElementType.POST_TRANSITION_METAL,
    symbol: 'Fl',
    name: 'Flerovium',
    period: 7,
    column: 14,
    atomicWeight: '(289)',
    electronAffinity: null,
    firstIonizationEnergy: null,
    secondIonizationEnergy: null,
    thirdIonizationEnergy: null,
  },
  {
    number: 115,
    type: null,
    symbol: 'Mc',
    name: 'Moscovium',
    period: 7,
    column: 15,
    atomicWeight: '(290)',
    electronAffinity: 35.3,
    firstIonizationEnergy: null,
    secondIonizationEnergy: null,
    thirdIonizationEnergy: null,
  },
  {
    number: 116,
    type: null,
    symbol: 'Lv',
    name: 'Livermorium',
    period: 7,
    column: 16,
    atomicWeight: '(293)',
    electronAffinity: 74.9,
    firstIonizationEnergy: null,
    secondIonizationEnergy: null,
    thirdIonizationEnergy: null,
  },
  {
    number: 117,
    type: null,
    symbol: 'Ts',
    name: 'Tennessine',
    period: 7,
    column: 17,
    atomicWeight: '(294)',
    electronAffinity: 165.9,
    firstIonizationEnergy: null,
    secondIonizationEnergy: null,
    thirdIonizationEnergy: null,
  },
  {
    number: 118,
    type: null,
    symbol: 'Og',
    name: 'Oganesson',
    period: 7,
    column: 18,
    atomicWeight: '(294)',
    electronAffinity: 5.403,
    firstIonizationEnergy: null,
    secondIonizationEnergy: null,
    thirdIonizationEnergy: null,
  },
]

export default elements
