export interface Element {
  number: number
  symbol: string
  name: string
  type: ElementType
  period: number
  column: number
  atomicWeight: number | string
  electronAffinity: number // TODO check these
  // ionizationEnergy: number
}

export enum ElementType {
  ALKALI_METAL,
  ALKALINE_EARTH_METAL,
  LANTHANOID,
  ACTINOID,
  TRANSITION_METAL,
  POST_TRANSITION_METAL,
  METALLOID,
  NOBLE_GAS,
  OTHER_NONMETAL,
}

const elements: Element[] = [
  {
    number: 1,
    type: ElementType.OTHER_NONMETAL,
    symbol: 'H',
    name: 'Hydrogen',
    period: 1,
    column: 1,
    atomicWeight: 1.008,
    electronAffinity: 72.8,
  },
  {
    number: 2,
    type: ElementType.NOBLE_GAS,
    symbol: 'He',
    name: 'Helium',
    period: 1,
    column: 18,
    atomicWeight: 4.0026,
    electronAffinity: 0,
  },
  {
    number: 3,
    type: ElementType.ALKALI_METAL,
    symbol: 'Li',
    name: 'Lithium',
    period: 2,
    column: 1,
    atomicWeight: 6.94,
    electronAffinity: 59.6,
  },
  {
    number: 4,
    type: ElementType.ALKALINE_EARTH_METAL,
    symbol: 'Be',
    name: 'Beryllium',
    period: 2,
    column: 2,
    atomicWeight: 9.0122,
    electronAffinity: 0,
  },
  {
    number: 5,
    type: ElementType.METALLOID,
    symbol: 'B',
    name: 'Boron',
    period: 2,
    column: 13,
    atomicWeight: 10.81,
    electronAffinity: 26.7,
  },
  {
    number: 6,
    type: ElementType.OTHER_NONMETAL,
    symbol: 'C',
    name: 'Carbon',
    period: 2,
    column: 14,
    atomicWeight: 12.011,
    electronAffinity: 153.9,
  },
  {
    number: 7,
    type: ElementType.OTHER_NONMETAL,
    symbol: 'N',
    name: 'Nitrogen',
    period: 2,
    column: 15,
    atomicWeight: 14.007,
    electronAffinity: 7,
  },
  {
    number: 8,
    type: ElementType.OTHER_NONMETAL,
    symbol: 'O',
    name: 'Oxygen',
    period: 2,
    column: 16,
    atomicWeight: 15.999,
    electronAffinity: 141,
  },
  {
    number: 9,
    type: ElementType.OTHER_NONMETAL,
    symbol: 'F',
    name: 'Fluorine',
    period: 2,
    column: 17,
    atomicWeight: 18.998,
    electronAffinity: 328,
  },
  {
    number: 10,
    type: ElementType.NOBLE_GAS,
    symbol: 'Ne',
    name: 'Neon',
    period: 2,
    column: 18,
    atomicWeight: 20.180,
    electronAffinity: 0,
  },
  {
    number: 11,
    type: ElementType.ALKALI_METAL,
    symbol: 'Na',
    name: 'Sodium',
    period: 3,
    column: 1,
    atomicWeight: 22.990,
    electronAffinity: 52.8,
  },
  {
    number: 12,
    type: ElementType.ALKALINE_EARTH_METAL,
    symbol: 'Mg',
    name: 'Magnesium',
    period: 3,
    column: 2,
    atomicWeight: 24.305,
    electronAffinity: 0,
  },
  {
    number: 13,
    type: ElementType.POST_TRANSITION_METAL,
    symbol: 'Al',
    name: 'Aluminium',
    period: 3,
    column: 13,
    atomicWeight: 26.982,
    electronAffinity: 42.5,
  },
  {
    number: 14,
    type: ElementType.METALLOID,
    symbol: 'Si',
    name: 'Silicon',
    period: 3,
    column: 14,
    atomicWeight: 28.085,
    electronAffinity: 133.6,
  },
  {
    number: 15,
    type: ElementType.OTHER_NONMETAL,
    symbol: 'P',
    name: 'Phosphorus',
    period: 3,
    column: 15,
    atomicWeight: 30.974,
    electronAffinity: 72,
  },
  {
    number: 16,
    type: ElementType.OTHER_NONMETAL,
    symbol: 'S',
    name: 'Sulfur',
    period: 3,
    column: 16,
    atomicWeight: 32.06,
    electronAffinity: 200,
  },
  {
    number: 17,
    type: ElementType.OTHER_NONMETAL,
    symbol: 'Cl',
    name: 'Chlorine',
    period: 3,
    column: 17,
    atomicWeight: 35.45,
    electronAffinity: 349,
  },
  {
    number: 18,
    type: ElementType.NOBLE_GAS,
    symbol: 'Ar',
    name: 'Argon',
    period: 3,
    column: 18,
    atomicWeight: 39.948,
    electronAffinity: 0,
  },
  {
    number: 19,
    type: ElementType.ALKALI_METAL,
    symbol: 'K',
    name: 'Potassium',
    period: 4,
    column: 1,
    atomicWeight: 39.098,
    electronAffinity: 48.4,
  },
  {
    number: 20,
    type: ElementType.ALKALINE_EARTH_METAL,
    symbol: 'Ca',
    name: 'Calcium',
    period: 4,
    column: 2,
    atomicWeight: 40.078,
    electronAffinity: 2.37,
  },
  {
    number: 21,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Sc',
    name: 'Scandium',
    period: 4,
    column: 3,
    atomicWeight: 44.956,
    electronAffinity: 18.1,
  },
  {
    number: 22,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Ti',
    name: 'Titanium',
    period: 4,
    column: 4,
    atomicWeight: 47.867,
    electronAffinity: 7.6,
  },
  {
    number: 23,
    type: ElementType.TRANSITION_METAL,
    symbol: 'V',
    name: 'Vanadium',
    period: 4,
    column: 5,
    atomicWeight: 50.942,
    electronAffinity: 50.6,
  },
  {
    number: 24,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Cr',
    name: 'Chromium',
    period: 4,
    column: 6,
    atomicWeight: 51.996,
    electronAffinity: 64.3,
  },
  {
    number: 25,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Mn',
    name: 'Manganese',
    period: 4,
    column: 7,
    atomicWeight: 54.938,
    electronAffinity: 0,
  },
  {
    number: 26,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Fe',
    name: 'Iron',
    period: 4,
    column: 8,
    atomicWeight: 55.845,
    electronAffinity: 15.7,
  },
  {
    number: 27,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Co',
    name: 'Cobalt',
    period: 4,
    column: 9,
    atomicWeight: 58.933,
    electronAffinity: 63.7,
  },
  {
    number: 28,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Ni',
    name: 'Nickel',
    period: 4,
    column: 10,
    atomicWeight: 58.693,
    electronAffinity: 112,
  },
  {
    number: 29,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Cu',
    name: 'Copper',
    period: 4,
    column: 11,
    atomicWeight: 63.546,
    electronAffinity: 118.4,
  },
  {
    number: 30,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Zn',
    name: 'Zinc',
    period: 4,
    column: 12,
    atomicWeight: 65.38,
    electronAffinity: 0,
  },
  {
    number: 31,
    type: ElementType.POST_TRANSITION_METAL,
    symbol: 'Ga',
    name: 'Gallium',
    period: 4,
    column: 13,
    atomicWeight: 69.723,
    electronAffinity: 28.9,
  },
  {
    number: 32,
    type: ElementType.METALLOID,
    symbol: 'Ge',
    name: 'Germanium',
    period: 4,
    column: 14,
    atomicWeight: 72.630,
    electronAffinity: 119,
  },
  {
    number: 33,
    type: ElementType.METALLOID,
    symbol: 'As',
    name: 'Arsenic',
    period: 4,
    column: 15,
    atomicWeight: 74.922,
    electronAffinity: 78,
  },
  {
    number: 34,
    type: ElementType.OTHER_NONMETAL,
    symbol: 'Se',
    name: 'Selenium',
    period: 4,
    column: 16,
    atomicWeight: 78.971,
    electronAffinity: 195,
  },
  {
    number: 35,
    type: ElementType.OTHER_NONMETAL,
    symbol: 'Br',
    name: 'Bromine',
    period: 4,
    column: 17,
    atomicWeight: 79.904,
    electronAffinity: 324.6,
  },
  {
    number: 36,
    type: ElementType.NOBLE_GAS,
    symbol: 'Kr',
    name: 'Krypton',
    period: 4,
    column: 18,
    atomicWeight: 83.798,
    electronAffinity: 0,
  },
  {
    number: 37,
    type: ElementType.ALKALI_METAL,
    symbol: 'Rb',
    name: 'Rubidium',
    period: 5,
    column: 1,
    atomicWeight: 85.468,
    electronAffinity: 46.9,
  },
  {
    number: 38,
    type: ElementType.ALKALINE_EARTH_METAL,
    symbol: 'Sr',
    name: 'Strontium',
    period: 5,
    column: 2,
    atomicWeight: 87.62,
    electronAffinity: 5.03,
  },
  {
    number: 39,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Y',
    name: 'Yttrium',
    period: 5,
    column: 3,
    atomicWeight: 88.906,
    electronAffinity: 29.6,
  },
  {
    number: 40,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Zr',
    name: 'Zirconium',
    period: 5,
    column: 4,
    atomicWeight: 91.224,
    electronAffinity: 41.1,
  },
  {
    number: 41,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Nb',
    name: 'Niobium',
    period: 5,
    column: 5,
    atomicWeight: 92.906,
    electronAffinity: 86.1,
  },
  {
    number: 42,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Mo',
    name: 'Molybdenum',
    period: 5,
    column: 6,
    atomicWeight: 95.95,
    electronAffinity: 71.9,
  },
  {
    number: 43,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Tc',
    name: 'Technetium',
    period: 5,
    column: 7,
    atomicWeight: '(98)',
    electronAffinity: 53,
  },
  {
    number: 44,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Ru',
    name: 'Ruthenium',
    period: 5,
    column: 8,
    atomicWeight: 101.07,
    electronAffinity: 101.3,
  },
  {
    number: 45,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Rh',
    name: 'Rhodium',
    period: 5,
    column: 9,
    atomicWeight: 102.91,
    electronAffinity: 109.7,
  },
  {
    number: 46,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Pd',
    name: 'Palladium',
    period: 5,
    column: 10,
    atomicWeight: 106.42,
    electronAffinity: 53.7,
  },
  {
    number: 47,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Ag',
    name: 'Silver',
    period: 5,
    column: 11,
    atomicWeight: 107.87,
    electronAffinity: 125.6,
  },
  {
    number: 48,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Cd',
    name: 'Cadmium',
    period: 5,
    column: 12,
    atomicWeight: 112.41,
    electronAffinity: 0,
  },
  {
    number: 49,
    type: ElementType.POST_TRANSITION_METAL,
    symbol: 'In',
    name: 'Indium',
    period: 5,
    column: 13,
    atomicWeight: 114.82,
    electronAffinity: 28.9,
  },
  {
    number: 50,
    type: ElementType.POST_TRANSITION_METAL,
    symbol: 'Sn',
    name: 'Tin',
    period: 5,
    column: 14,
    atomicWeight: 118.71,
    electronAffinity: 107.3,
  },
  {
    number: 51,
    type: ElementType.METALLOID,
    symbol: 'Sb',
    name: 'Antimony',
    period: 5,
    column: 15,
    atomicWeight: 121.76,
    electronAffinity: 103.2,
  },
  {
    number: 52,
    type: ElementType.METALLOID,
    symbol: 'Te',
    name: 'Tellurium',
    period: 5,
    column: 16,
    atomicWeight: 127.60,
    electronAffinity: 190.2,
  },
  {
    number: 53,
    type: ElementType.OTHER_NONMETAL,
    symbol: 'I',
    name: 'Iodine',
    period: 5,
    column: 17,
    atomicWeight: 126.90,
    electronAffinity: 295.2,
  },
  {
    number: 54,
    type: ElementType.NOBLE_GAS,
    symbol: 'Xe',
    name: 'Xenon',
    period: 5,
    column: 18,
    atomicWeight: 131.29,
    electronAffinity: 0,
  },
  {
    number: 55,
    type: ElementType.ALKALI_METAL,
    symbol: 'Cs',
    name: 'Caesium',
    period: 6,
    column: 1,
    atomicWeight: 132.91,
    electronAffinity: 45.5,
  },
  {
    number: 56,
    type: ElementType.ALKALINE_EARTH_METAL,
    symbol: 'Ba',
    name: 'Barium',
    period: 6,
    column: 2,
    atomicWeight: 137.33,
    electronAffinity: 13.95,
  },
  {
    number: 57,
    type: ElementType.LANTHANOID,
    symbol: 'La',
    name: 'Lanthanum',
    period: 6,
    column: null,
    atomicWeight: 138.91,
    electronAffinity: 48,
  },
  {
    number: 58,
    type: ElementType.LANTHANOID,
    symbol: 'Ce',
    name: 'Cerium',
    period: 6,
    column: null,
    atomicWeight: 140.12,
    electronAffinity: 50,
  },
  {
    number: 59,
    type: ElementType.LANTHANOID,
    symbol: 'Pr',
    name: 'Praseodymium',
    period: 6,
    column: null,
    atomicWeight: 140.91,
    electronAffinity: 50,
  },
  {
    number: 60,
    type: ElementType.LANTHANOID,
    symbol: 'Nd',
    name: 'Neodymium',
    period: 6,
    column: null,
    atomicWeight: 144.24,
    electronAffinity: 50,
  },
  {
    number: 61,
    type: ElementType.LANTHANOID,
    symbol: 'Pm',
    name: 'Promethium',
    period: 6,
    column: null,
    atomicWeight: '(145)',
    electronAffinity: 50,
  },
  {
    number: 62,
    type: ElementType.LANTHANOID,
    symbol: 'Sm',
    name: 'Samarium',
    period: 6,
    column: null,
    atomicWeight: 150.36,
    electronAffinity: 50,
  },
  {
    number: 63,
    type: ElementType.LANTHANOID,
    symbol: 'Eu',
    name: 'Europium',
    period: 6,
    column: null,
    atomicWeight: 151.96,
    electronAffinity: 50,
  },
  {
    number: 64,
    type: ElementType.LANTHANOID,
    symbol: 'Gd',
    name: 'Gadolinium',
    period: 6,
    column: null,
    atomicWeight: 157.25,
    electronAffinity: 50,
  },
  {
    number: 65,
    type: ElementType.LANTHANOID,
    symbol: 'Tb',
    name: 'Terbium',
    period: 6,
    column: null,
    atomicWeight: 158.93,
    electronAffinity: 50,
  },
  {
    number: 66,
    type: ElementType.LANTHANOID,
    symbol: 'Dy',
    name: 'Dysprosium',
    period: 6,
    column: null,
    atomicWeight: 162.50,
    electronAffinity: 50,
  },
  {
    number: 67,
    type: ElementType.LANTHANOID,
    symbol: 'Ho',
    name: 'Holmium',
    period: 6,
    column: null,
    atomicWeight: 164.93,
    electronAffinity: 50,
  },
  {
    number: 68,
    type: ElementType.LANTHANOID,
    symbol: 'Er',
    name: 'Erbium',
    period: 6,
    column: null,
    atomicWeight: 167.26,
    electronAffinity: 50,
  },
  {
    number: 69,
    type: ElementType.LANTHANOID,
    symbol: 'Tm',
    name: 'Thulium',
    period: 6,
    column: null,
    atomicWeight: 168.93,
    electronAffinity: 50,
  },
  {
    number: 70,
    type: ElementType.LANTHANOID,
    symbol: 'Yb',
    name: 'Ytterbium',
    period: 6,
    column: null,
    atomicWeight: 173.05,
    electronAffinity: 50,
  },
  {
    number: 71,
    type: ElementType.LANTHANOID,
    symbol: 'Lu',
    name: 'Lutetium',
    period: 6,
    column: null,
    atomicWeight: 174.97,
    electronAffinity: 50,
  },
  {
    number: 72,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Ha',
    name: 'Hafnium',
    period: 6,
    column: 4,
    atomicWeight: 178.49,
    electronAffinity: 0,
  },
  {
    number: 73,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Tf',
    name: 'Tantalum',
    period: 6,
    column: 5,
    atomicWeight: 180.95,
    electronAffinity: 31,
  },
  {
    number: 74,
    type: ElementType.TRANSITION_METAL,
    symbol: 'W',
    name: 'Tungsten',
    period: 6,
    column: 6,
    atomicWeight: 183.84,
    electronAffinity: 78.6,
  },
  {
    number: 75,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Re',
    name: 'Rhenium',
    period: 6,
    column: 7,
    atomicWeight: 186.21,
    electronAffinity: 14.5,
  },
  {
    number: 76,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Os',
    name: 'Osmium',
    period: 6,
    column: 8,
    atomicWeight: 190.23,
    electronAffinity: 106.1,
  },
  {
    number: 77,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Ir',
    name: 'Iridium',
    period: 6,
    column: 9,
    atomicWeight: 192.22,
    electronAffinity: 151,
  },
  {
    number: 78,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Pt',
    name: 'Platinum',
    period: 6,
    column: 10,
    atomicWeight: 195.08,
    electronAffinity: 205.3,
  },
  {
    number: 79,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Ag',
    name: 'Gold',
    period: 6,
    column: 11,
    atomicWeight: 196.97,
    electronAffinity: 222.8,
  },
  {
    number: 80,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Hg',
    name: 'Mercury',
    period: 6,
    column: 12,
    atomicWeight: 200.59,
    electronAffinity: 0,
  },
  {
    number: 81,
    type: ElementType.POST_TRANSITION_METAL,
    symbol: 'Tl',
    name: 'Thallium',
    period: 6,
    column: 13,
    atomicWeight: 204.38,
    electronAffinity: 19.2,
  },
  {
    number: 82,
    type: ElementType.POST_TRANSITION_METAL,
    symbol: 'Pb',
    name: 'Lead',
    period: 6,
    column: 14,
    atomicWeight: 207.2,
    electronAffinity: 35.1,
  },
  {
    number: 83,
    type: ElementType.POST_TRANSITION_METAL,
    symbol: 'Bi',
    name: 'Bismuth',
    period: 6,
    column: 15,
    atomicWeight: 208.98,
    electronAffinity: 91.2,
  },
  {
    number: 84,
    type: ElementType.POST_TRANSITION_METAL,
    symbol: 'Po',
    name: 'Polonium',
    period: 6,
    column: 16,
    atomicWeight: '(209)',
    electronAffinity: 183.3,
  },
  {
    number: 85,
    type: ElementType.METALLOID,
    symbol: 'At',
    name: 'Astatine',
    period: 6,
    column: 17,
    atomicWeight: '(210)',
    electronAffinity: 270.1,
  },
  {
    number: 86,
    type: ElementType.NOBLE_GAS,
    symbol: 'Rn',
    name: 'Radon',
    period: 6,
    column: 18,
    atomicWeight: '(222)',
    electronAffinity: 0,
  },
  {
    number: 87,
    type: ElementType.ALKALI_METAL,
    symbol: 'Fr',
    name: 'Francium',
    period: 7,
    column: 1,
    atomicWeight: '(223)',
    electronAffinity: null,
  },
  {
    number: 88,
    type: ElementType.ALKALI_METAL,
    symbol: 'Ra',
    name: 'Radium',
    period: 7,
    column: 2,
    atomicWeight: '(226)',
    electronAffinity: null,
  },
  {
    number: 89,
    type: ElementType.ACTINOID,
    symbol: 'Ac',
    name: 'Actinium',
    period: 7,
    column: null,
    atomicWeight: '(227)',
    electronAffinity: null,
  },
  {
    number: 90,
    type: ElementType.ACTINOID,
    symbol: 'Th',
    name: 'Thorium',
    period: 7,
    column: null,
    atomicWeight: 232.04,
    electronAffinity: null,
  },
  {
    number: 91,
    type: ElementType.ACTINOID,
    symbol: 'Pa',
    name: 'Protactinium',
    period: 7,
    column: null,
    atomicWeight: 231.04,
    electronAffinity: null,
  },
  {
    number: 92,
    type: ElementType.ACTINOID,
    symbol: 'U',
    name: 'Uranium',
    period: 7,
    column: null,
    atomicWeight: 238.03,
    electronAffinity: null,
  },
  {
    number: 93,
    type: ElementType.ACTINOID,
    symbol: 'Np',
    name: 'Neptunium',
    period: 7,
    column: null,
    atomicWeight: '(237)',
    electronAffinity: null,
  },
  {
    number: 94,
    type: ElementType.ACTINOID,
    symbol: 'Pu',
    name: 'Plutonium',
    period: 7,
    column: null,
    atomicWeight: '(244)',
    electronAffinity: null,
  },
  {
    number: 95,
    type: ElementType.ACTINOID,
    symbol: 'Am',
    name: 'Americium',
    period: 7,
    column: null,
    atomicWeight: '(243)',
    electronAffinity: null,
  },
  {
    number: 96,
    type: ElementType.ACTINOID,
    symbol: 'Cm',
    name: 'Curium',
    period: 7,
    column: null,
    atomicWeight: '(247)',
    electronAffinity: null,
  },
  {
    number: 97,
    type: ElementType.ACTINOID,
    symbol: 'Bk',
    name: 'Berkelium',
    period: 7,
    column: null,
    atomicWeight: '(247)',
    electronAffinity: null,
  },
  {
    number: 98,
    type: ElementType.ACTINOID,
    symbol: 'Cf',
    name: 'Californium',
    period: 7,
    column: null,
    atomicWeight: '(251)',
    electronAffinity: null,
  },
  {
    number: 99,
    type: ElementType.ACTINOID,
    symbol: 'Es',
    name: 'Einsteinium',
    period: 7,
    column: null,
    atomicWeight: '(252)',
    electronAffinity: null,
  },
  {
    number: 100,
    type: ElementType.ACTINOID,
    symbol: 'Fm',
    name: 'Fermium',
    period: 7,
    column: null,
    atomicWeight: '(257)',
    electronAffinity: null,
  },
  {
    number: 101,
    type: ElementType.ACTINOID,
    symbol: 'Md',
    name: 'Mendelevium',
    period: 7,
    column: null,
    atomicWeight: '(258)',
    electronAffinity: null,
  },
  {
    number: 102,
    type: ElementType.ACTINOID,
    symbol: 'No',
    name: 'Nobelium',
    period: 7,
    column: null,
    atomicWeight: '(259)',
    electronAffinity: null,
  },
  {
    number: 103,
    type: ElementType.ACTINOID,
    symbol: 'Lr',
    name: 'Lawrencium',
    period: 7,
    column: null,
    atomicWeight: '(266)',
    electronAffinity: null,
  },
  {
    number: 104,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Rf',
    name: 'Rutherfordium',
    period: 7,
    column: 4,
    atomicWeight: '(267)',
    electronAffinity: null,
  },
  {
    number: 105,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Db',
    name: 'Dubnium',
    period: 7,
    column: 5,
    atomicWeight: '(268)',
    electronAffinity: null,
  },
  {
    number: 106,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Sg',
    name: 'Seaborgium',
    period: 7,
    column: 6,
    atomicWeight: '(269)',
    electronAffinity: null,
  },
  {
    number: 107,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Bh',
    name: 'Bohrium',
    period: 7,
    column: 7,
    atomicWeight: '(270)',
    electronAffinity: null,
  },
  {
    number: 108,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Hs',
    name: 'Hassium',
    period: 7,
    column: 8,
    atomicWeight: '(270)',
    electronAffinity: null,
  },
  {
    number: 109,
    type: null,
    symbol: 'Mt',
    name: 'Meitnerium',
    period: 7,
    column: 9,
    atomicWeight: '(278)',
    electronAffinity: null,
  },
  {
    number: 110,
    type: null,
    symbol: 'Ds',
    name: 'Darmstadtium',
    period: 7,
    column: 10,
    atomicWeight: '(281)',
    electronAffinity: null,
  },
  {
    number: 111,
    type: null,
    symbol: 'Rg',
    name: 'Roentgenium',
    period: 7,
    column: 11,
    atomicWeight: '(282)',
    electronAffinity: null,
  },
  {
    number: 112,
    type: ElementType.TRANSITION_METAL,
    symbol: 'Cn',
    name: 'Copernicium',
    period: 7,
    column: 12,
    atomicWeight: '(285)',
    electronAffinity: null,
  },
  {
    number: 113,
    type: null,
    symbol: 'Nh',
    name: 'Nihonium',
    period: 7,
    column: 13,
    atomicWeight: '(286)',
    electronAffinity: null,
  },
  {
    number: 114,
    type: ElementType.POST_TRANSITION_METAL,
    symbol: 'Fl',
    name: 'Flerovium',
    period: 7,
    column: 14,
    atomicWeight: '(289)',
    electronAffinity: null,
  },
  {
    number: 115,
    type: null,
    symbol: 'Mc',
    name: 'Moscovium',
    period: 7,
    column: 15,
    atomicWeight: '(290)',
    electronAffinity: null,
  },
  {
    number: 116,
    type: null,
    symbol: 'Lv',
    name: 'Livermorium',
    period: 7,
    column: 16,
    atomicWeight: '(293)',
    electronAffinity: null,
  },
  {
    number: 117,
    type: null,
    symbol: 'Ts',
    name: 'Tennessine',
    period: 7,
    column: 17,
    atomicWeight: '(294)',
    electronAffinity: null,
  },
  {
    number: 118,
    type: null,
    symbol: 'Og',
    name: 'Oganesson',
    period: 7,
    column: 18,
    atomicWeight: '(294)',
    electronAffinity: null,
  },
]

export default elements
